### ISSUE TITLE
Bugs:

### ISSUE THREAD

**Issue by ghost** [RSDuck/craftus_reloaded#10]
- Bugs (Found in version 0.3 Pre-2):
1. After 2-3 minutes of play, I get an ARM9 error. (I do not know if it's just me, but I'll also report it).
2. By jumping several times in front of a wall, you stay as if you were hooked to the wall.
3. When creating a new world (Superflat), I got the white screen, and I had to restart the 3DS.

**Comment by RSDuck** [comment]
please try pre release 2 of 0.3, it addressed a lot of these issues
