### ISSUE TITLE
Crash while playing the game

### ISSUE THREAD

**Issue by jj20466** [RSDuck/craftus_reloaded#2]
[crash_dump_00000016.dmp.zip](https://github.com/RSDuck/craftus_reloaded/files/1255057/crash_dump_00000016.dmp.zip)
I was playing the game yesterday when it crashed all of a sudden mid build and this came up
![20170827_160421](https://user-images.githubusercontent.com/30852004/29758458-4eeae472-8be6-11e7-9153-5772e3957363.jpg)
Then i went to the location and found the dump file so you can look at and is there a way for you to turn auto jump off or fix it cause when ever i bump into a wall it makes me jump.

**Comment by RSDuck** [comment]
I looked into the crash and I think it's related to file I/O but I'm still not sure. Can you reproduce the crash, or did it happen only once? 
And if you don't mind, can you please send me the save folder of the world?
You're probably playing on a n3ds. I always forget about them. I have to disable the auto jumping on nd3ses and improve so that it is more like MC PE.

**Comment by jj20466** [comment]
I would love to recreate the error but it deleted most of my build and i
dont know how i did it,i was making a castle and i had the outside walls
with towers on each corner then i started outlining the main building/house
on the inside and as i was making the second floor the game crashed then
the error popped up.
[ffg.zip](https://github.com/RSDuck/craftus_reloaded/files/1256627/ffg.zip)

.

**Comment by RSDuck** [comment]
this issue seems to be one of these where it's hard to find the orgin, because they can't really be reproduced.

I really hope I fixed this issue, but I let the issue open, it might happen once again

**Comment by jj20466** [comment]
Game crashed again,only thing i did before it crashed was jump by pressing the button then landing on a block in front of me i think about a block or two away.
[crash data.zip](https://github.com/RSDuck/craftus_reloaded/files/1262407/crash.data.zip)

**Comment by jj20466** [comment]
I took a screenshot of what i was doing this time after the game crashed.
![20170830_122845](https://user-images.githubusercontent.com/30852004/29855657-f8ff391e-8d7f-11e7-90d8-f9107252ad47.jpg)
All i was doing was looking down while holding the place block button and slowly moving forward to build the wall 
[crash data new.zip](https://github.com/RSDuck/craftus_reloaded/files/1262431/crash.data.new.zip)

**Comment by RSDuck** [comment]
I think, I fixed this issue, but if someone experiences a similar error again, please reopen this issue
