### ISSUE TITLE
compilation problem

### ISSUE THREAD

**Issue by cooolgamer** [RSDuck/craftus_reloaded#21]
hello, I have a problem by compiling the code:
![image](https://user-images.githubusercontent.com/64099608/99188828-5025dd80-275e-11eb-8697-05a58e80f8cb.png)

It's possible to help me?
Thanks.

**Comment by RSDuck** [comment]
apparently that function got deprecated and removed. See https://github.com/devkitPro/citro3d/commit/8d8979947eed7e1c0422250b425463bd85737742#diff-dd58542c94992759a34ee314252c741a1f62d96ea97eb02ed92caa4848023072L66

**Comment by cooolgamer** [comment]
oh... But how can I compile it now? :/

**Comment by RSDuck** [comment]
by changing so that it doesn't use the deprecated function anymore. Then make a PR and I'll merge it 😄

**Comment by cooolgamer** [comment]
ouch... I don't understand

**Comment by RSDuck** [comment]
I suggested that you fix it, though I figured it wasn't so hard so I did it myself.

**Comment by cooolgamer** [comment]
nvm, craftus reskined work, I don't need help anymore, thanks you anyways 👍
