### ISSUE TITLE
Error when compiling

### ISSUE THREAD

**Issue by pascoid** [RSDuck/craftus_reloaded#22]
Get this error when compiling, any help?

![image](https://user-images.githubusercontent.com/68710005/100002849-ec299780-2da3-11eb-89ae-3675f792366b.png)

**Comment by RSDuck** [comment]
I think you need to install the package 3dstools (run `pacman -S 3dstools`)

**Comment by pascoid** [comment]
Thanks! it worked! I feel very dumb for not trying that before.
