### ISSUE TITLE
About Craftus

### ISSUE THREAD

**Issue by pascoid** [RSDuck/craftus_reloaded#23]
I already started a project called Craftus Reskined, its just Craftus Reloaded with Minecraft's texture, but I am adding more blocks and features, you mind if I continue doing so?

**Comment by RSDuck** [comment]
you can't use Minecraft's textures, because they're copyrighted, while the texturepack I used (Pixel Perfection by XSSheep) is licensed under CC-BY-SA. As long as you keep original Minecraft assets out of this, I'll gladly accept PRs.

**Comment by pascoid** [comment]
Thanks, I will change the textures in a new release.
