### ISSUE TITLE
Some more issues

### ISSUE THREAD

**Issue by DevShadd** [RSDuck/craftus_reloaded#5]
I found some more issues while playing around for a little.
►Highligted blocks can be seen through any block in the way.
►Sometimes character gets stuck while walking forward up a mountain and requires you to back up or stop on moving to be able to jump over it (both automatical jumps and manual jumps)

Unkown issues:
►When looking down to the ground on the O3DS, sky appears yellowish, then turns back to blue when you look back up

The unknown issue is an issue that I'm not sure if it is a bug because of the system's fault or just the game's bug.

**Comment by Auscobe** [comment]
I've Experienced (1) Once or twice, haven't ran into (2), and may or may not have ran into (3), but i can't test it because my 3DS has a physical issue that may be resolvable.
(i've just been commenting to make it clear that these issues can be replicated at least by me)
Also, looks to me like your gonna be quite helpful to this repo and game development. GG.

**Comment by DevShadd** [comment]
I got the character stuck a few times which both makes me laugh and frustrated. lol
When the blocks get fully highlighted and you can see the highlighted block through another block in the way (basically hover over a half-hidden block and then you will be able to see this) which makes the game feel less polished.

BTW, I experienced the unknown issue on a Red O3DS (if the color matters), not the XL version.

**Comment by Auscobe** [comment]
The color of the 3DS has nothing to do with it, even if it's XL or not (unless we'd be talking 2DS i think) it's still the same hardware.

**Comment by RSDuck** [comment]
I think everything here mentioned was fixed in the latest release. The last bug can be fixed by disabling power saving mode on your 3ds.
