### ISSUE TITLE
Build Height Limit (?)

### ISSUE THREAD

**Issue by ghost** [RSDuck/craftus_reloaded#6]
The game freezes once you got past a certain point vertically. Once froze, you have to force-shutdown, and any progress made in that session is lost. Have tried multiple times, all froze around 37-8 blocks above clouds. World type: smea. O2DS Luma v8.1 11.5 running latest craftus .cia release
![photo0092](https://user-images.githubusercontent.com/32059607/30770230-200f8cf4-a07f-11e7-9faf-930ba1effbb4.jpg)

**Comment by LockonMeister** [comment]
Forgot to mention that you have to force-shutdown, any progress made in that session is lost.

**Comment by RSDuck** [comment]
indeed, you reached the world limit, the world is 128 blocks high. The latest commit should have fixed it, but I leave this issue open until the next release

**Comment by RSDuck** [comment]
Can you try to reproduce the crash with the latest release? It should be fixed by now

**Comment by ghost** [comment]
It's fixed, cannot reproduce, tested multiple times
