### ISSUE TITLE
[Feedback] Amazing Minecraft Clone

### ISSUE THREAD

**Issue by SSQ123** [RSDuck/craftus_reloaded#9]
I couldn't even get 3DScraft to work and Craftus Reloaded is an amazing 3ds minecraft clone.

**Comment by cohaereo** [comment]
RSDuck is probably happy with your feedback, but next time avoid using the issues section

**Comment by SSQ123** [comment]
Where should I have put it?

**Comment by RSDuck** [comment]
Thank you for your appreciation. Like @firewolfgames said, please only report bugs/request specific features here on Github. 
The thread on Gbatemp is probably more appropriate for this kind of feedback. Also simply starring is also a way to show your appreciation.
